### ISSUE TITLE
Mobs Becoming Invisible Once You Die

### ISSUE THREAD

**Issue by Jumbles233** [ProsperCraft/towncraft#10]
The title says it all.  The only way to fix this issue is to relog out of single player worlds, but if you die again (which is pretty common when you're at your grave and surrounded by the same mobs) the issue returns.

**Comment by ProsperCraft** [comment]
Single player or server? 
What forge version are you using?
did you modify the pack in any way?
Did you add optifine?
What graphics card?
Are your graphics card drivers up to date?
Is your java up to date with 181 64 bit?
How much ram do you allocate to the pack?

Nobody else has reported this problem, and playing on the official server we are not having this issue.
