### ISSUE TITLE
Issue about the questing

### ISSUE THREAD

**Issue by KazeSoftworks** [ProsperCraft/towncraft#11]
Hi, enjoying the modpack with some friends on my server so far, just some things that i have crossed by:

- The quests about the planes, all of them show "Item Placeholder" and won't accept the planes they are supposed to accept, making it impossible to progress.

- The fuel pump quest says that it needs lava and that it was going to be changed later, but as for now, the fuel pump only accepts Gasoline from the Immersive Petroleum, it can be a bit misleading for new player that does not have much experience with liquids that could work with it, I don't know if is possible to also add other kinds of fuel (like IC2 biofuel and Refined Fuel and the other fuels that thermal expansion has)

- Since the killing quests were way bugged and got removed, I wonder if there are any other method to get the Dark Medieval Roleplay Coins, or if any other quest can be added to get them, since they are used for other quests and could greatly help players since the rewards for them are very good.

**Comment by ProsperCraft** [comment]
Quests updated.
