### ISSUE TITLE
Neon Engine/Flux Transformer not working as intended

### ISSUE THREAD

**Issue by xShadowofIntentx** [ProsperCraft/towncraft#13]
When trying to use the Flux transformer, It doesn't Convert from Neon Energy to Flux, it converts Flux to Neon. This should be how the Neon Engine functions, but it will not connect to any cables to input/output power. Was sent over here from the Futurepack Curse page to report the issue. 
( https://minecraft.curseforge.com/projects/futurepack )

**Comment by ProsperCraft** [comment]
This is the desired case as solars are nerfed in the pack.
