### ISSUE TITLE
Not Teleporting portal

### ISSUE THREAD

**Issue by ym1025** [ProsperCraft/towncraft#14]
I died at Huge Cavern Dimension. I Respawned,used the grave key. I Teleported at the grave. I could never return afterwards.(I'm not good at English)
Towncraft version:2.51

**Comment by AGiantDino** [comment]
I had the same issue and I'm not sure of a way to fix it the "right" way.  set your gamemode to creative or turn cheats on and give yourself a teleporter from the customnpc's mod and you can warp to the overworld and you can at least get out of the cavern dimension.

**Comment by ProsperCraft** [comment]
reported to the mod author several times.
