### ISSUE TITLE
Server Console Spammed By "hydrophobia" counter

### ISSUE THREAD

**Issue by rmnaderdev** [ProsperCraft/towncraft#15]
Just set up a server today for my modded community and my server console is spamming a countdown 
 and resetting to a 25000 that looks something like this:
`[21:14:44] [Server thread/INFO] [hydrophobia]: 22159`
`[21:14:44] [Server thread/INFO] [hydrophobia]: 22158`
`[21:14:44] [Server thread/INFO] [hydrophobia]: 22157`
`[21:14:44] [Server thread/INFO] [hydrophobia]: 22156`
...
It makes the server console almost un-usable.

**Comment by ProsperCraft** [comment]
Disable hydrophobia, then start your server.

**Comment by nullKomplex** [comment]
Alternatively you may update the mod to the latest version.
