### ISSUE TITLE
Items not stacking

### ISSUE THREAD

**Issue by Yuna85** [ProsperCraft/towncraft#16]
I have encountered a bug on Towncraft where Items will stay in multiple unfinished stacks even though they should definitely stack (had it with coal, bread, iron ingots, apples and gunpowder so far) it is really annoying cause it's clogging up the inventory so fast xD any ideas what to do about this?

**Comment by ProsperCraft** [comment]
https://github.com/pWn3d1337/Techguns/issues/138

Known issue and author will fix in "next version" his last curse release was a year ago.
