### ISSUE TITLE
Completing non existent quests

### ISSUE THREAD

**Issue by SevenChords** [ProsperCraft/towncraft#18]
Hey, i have had about 20 quest completed notifications by now, that don't show up in the questbook, which i find rather strange, these include "kill bandits", with one of the rifles/smgs as icon, "the beginning" with a stone block as icon, and many more, and i just can't find them anywhere in the questbook.

**Comment by ProsperCraft** [comment]
Funwayguy added a command for me - /bq_admin purge_hidden_quests

Cleaned up 103 hidden quests :)
