### ISSUE TITLE
Questing Issue: Techguns

### ISSUE THREAD

**Issue by genthug** [ProsperCraft/towncraft#21]
In the Techguns tree, two of the quests in the carbon progression are identical (the two circled in blue below). I assume the quest further in the quest line was to make carbon mechanical parts, as that is what the icon is for.

![image](https://user-images.githubusercontent.com/15116431/57575474-ae129000-7418-11e9-8f23-71e5f7b86355.png)

**Comment by genthug** [comment]
Mining Suit quest:

Miner's Helmet and Miner's Pants would not register, had to turn on ignoreNBT to have them register.

**Comment by genthug** [comment]
Techguns Tree: Cybernetic Parts quest:
Unseen "Kill CyberDemons" quest needs to have ignoreNBT turned on to register the CyberDemons being killed.

**Comment by ProsperCraft** [comment]
Quests updated.
