### ISSUE TITLE
Problems with quests in some branches

### ISSUE THREAD

**Issue by ImDredd** [ProsperCraft/towncraft#22]
Tab - minecolonies qest building tool 
![image](https://user-images.githubusercontent.com/50588864/57634110-55283080-75ad-11e9-957c-a3304cd476d7.png)

Could not pass due to the fact that the item was not found

**Comment by ImDredd** [comment]
![image](https://user-images.githubusercontent.com/50588864/57634206-86086580-75ad-11e9-8478-3ed8ac7186fa.png)
Same problem tab-creating your town qest-Vanila.chisel.star trek and Spawn eggs

**Comment by ImDredd** [comment]
![image](https://user-images.githubusercontent.com/50588864/57634310-bfd96c00-75ad-11e9-8ce3-7df7f9ae12bf.png)

**Comment by ImDredd** [comment]
I think that there may be more problems with quests, I found only those that are available immediately at the beginning about what could be next, I can not know.

**Comment by ImDredd** [comment]
I consider assembly one of the best I've seen, I would like to know how soon you can solve this problem?

**Comment by Chris-FireFox** [comment]
There are issues with the futurepack "another tech table?" taht requires you to get an Opti Bench. the quest is not registering the craft bench. possibly due to the bench having various different modules it could come installed with (different ram, cores and chipsets)

**Comment by bvierra** [comment]
Hey all,

I have fixed all the quests that had the wrong item names (was caused by the MTS addon pack updating the naming scheme).

Download the file from: https://gist.github.com/bvierra/03a63d3ed84255885fe06e09e7d2a4b1

You just put it in mods/betterquesting/DefaultQuests.json

then in game run:
`/bq_admin default load`

`/bq_user refresh`

**Comment by ProsperCraft** [comment]
@bvierra Very nice, did you fix the minecolonies wand as well due to an update in that mod as well?

if so I will swap out the quest file.

**Comment by bvierra** [comment]
Yep, I fixed like 15 different ones (including all the planes) anything I could find :)

**Comment by ProsperCraft** [comment]
Fixes included in the latest release.  Thank you.
