### ISSUE TITLE
Server crash on start up

### ISSUE THREAD

**Issue by dvl180** [ProsperCraft/towncraft#24]
[crash-2019-05-23_08.50.28-server.txt](https://github.com/ProsperCraft/towncraft/files/3209889/crash-2019-05-23_08.50.28-server.txt)

Crashes on start up each time, I'm not good at reading crash logs.

**Comment by ProsperCraft** [comment]
You have lagoggles spongeforge version, do you have spongeforge in your mods?  

The crash is related to sponge mixins.
