### ISSUE TITLE
Crafting Conflicts

### ISSUE THREAD

**Issue by SomeRandomPetey** [ProsperCraft/towncraft#25]
I've noticed a few crafting conflicts that don't let me craft certain items, such as the Grass Roof Block from ChinjufuMod. I'd personally reccommend adding NoMore Recipe Conflict, which fixes the issue of conflicting recipes.
Link:
https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

**Comment by ProsperCraft** [comment]
Please file a new issue including exact recipe conflicts so we can resolve them.

We don't need nomorerecipieconflits as the forestry worktable already does this.
