### ISSUE TITLE
[Towncraft][Official Server] Quest fails to detect

### ISSUE THREAD

**Issue by giddorah** [ProsperCraft/towncraft#28]
In the Mekanism quest-line, I can't seem to complete the "Ore Processing - Tier 0" quest however I try.

I have tried creating an Energized Smelter. Not detected
I have tried holding it in my hand. Not detected
I have tried adding it to my inventory. Not detected
Placing it. Not detected
Destroying it. Not detected
Relogging with it in my hand. Not detected
Creating another one. Not detected
Running the command for refreshing local quest thingy. Not detected

It seems to be broken, sir

**Comment by mummabia** [comment]
I too had this issue on the same quest.  Quest "Only the pure shall advance" also did not detect.  Thanks.

**Comment by ben-mkiv** [comment]
Same for the FuturePack Opti Bench (might depend on the color you craft, or whatever it compares)

**Comment by ProsperCraft** [comment]
I revamped almost all of the machine quests as the mod updates borked them all.
