### ISSUE TITLE
Quests not working

### ISSUE THREAD

**Issue by Dioxane** [ProsperCraft/towncraft#3]
I've only been able to claim the logs, and planks quests. Been unable to claim any other quests from the BQ book. I've turned off bq_admin edit. Does not complete on the official server, single player, or on my own server.

**Comment by ProsperCraft** [comment]
Are you still having this issue?

**Comment by Dioxane** [comment]
I haven't updated anything, nor have I launched the pack since as I'm mostly trapped without any means to progress.

**Comment by ProsperCraft** [comment]
To get the quest updates you need to update the pack.  Please update and advise.
