### ISSUE TITLE
Quest book

### ISSUE THREAD

**Issue by MisterVirtual** [ProsperCraft/towncraft#32]
Please fix the questline for completing "mossy stone". It claims to have 2 requirements to complete, but only one shows up and the quest cannot be completed, even after making the portal and passing through.

**Comment by ProsperCraft** [comment]
The quest logic is OR so it should complete with mossy cobble or mossy bricks.

**Comment by ProsperCraft** [comment]
Something is up with Better Questing, removed the second or task for mossy bricks so it only works with mossy cobble, fixed. tested.
