### ISSUE TITLE
recipe for gunpowder using sulfur does not work

### ISSUE THREAD

**Issue by jimmon89** [ProsperCraft/towncraft#33]
Jei lists gunpowder as an output for crafting 4 sulfur in a 2x2 grid,
screenshots included for reference
![2019-12-31_19 22 05](https://user-images.githubusercontent.com/6391541/71636801-7eaccf80-2c03-11ea-92ce-51fa8910d5af.png)
![2019-12-31_19 22 15](https://user-images.githubusercontent.com/6391541/71636802-7eaccf80-2c03-11ea-8e57-84a9b8b47326.png)
![2019-12-31_19 22 32](https://user-images.githubusercontent.com/6391541/71636803-7eaccf80-2c03-11ea-9862-4fa5bbd4affc.png)
![2019-12-31_19 23 36](https://user-images.githubusercontent.com/6391541/71636804-7eaccf80-2c03-11ea-97a1-9c678ea59bc2.png)

**Comment by ProsperCraft** [comment]
Fixed.
