### ISSUE TITLE
[Towncraft] Techguns mining armor quest not complete-able

### ISSUE THREAD

**Issue by jimmon89** [ProsperCraft/towncraft#36]
the armor needed to complete the quest, in the following pictures it displays that the quest asks for pieces with "No Camo" but such a set is unobtainable without creative mode
even with the camo bench

what the quest asks for
![quest_boot](https://user-images.githubusercontent.com/6391541/71786545-75907980-2fda-11ea-82d4-768278ad6511.png)
![quest_chest](https://user-images.githubusercontent.com/6391541/71786546-75907980-2fda-11ea-92a1-236b3177a6af.png)
![quest_helm](https://user-images.githubusercontent.com/6391541/71786547-75907980-2fda-11ea-8e7c-2d6dd4d6df5d.png)
![quest_pant](https://user-images.githubusercontent.com/6391541/71786548-76291000-2fda-11ea-87f4-9c143ee2c7d5.png)
--------------------------------------------------------
what is crafted
![craft_boot](https://user-images.githubusercontent.com/6391541/71786558-86d98600-2fda-11ea-95c8-5c90c088a4cb.png)
![craft_chest](https://user-images.githubusercontent.com/6391541/71786559-86d98600-2fda-11ea-8874-37a12b4a46a0.png)
![craft_helm](https://user-images.githubusercontent.com/6391541/71786560-86d98600-2fda-11ea-93c2-bd4c3c62dc65.png)
![craft_pant](https://user-images.githubusercontent.com/6391541/71786561-86d98600-2fda-11ea-9b57-0ff0c91ee57f.png)

**Comment by ProsperCraft** [comment]
This may be fixed now, I enabled partial match option.
