### ISSUE TITLE
[Immersive Vehicles Trin Part Pack Mods] Engines crafted have chances of being bugged

### ISSUE THREAD

**Issue by Linux-MissingNo** [ProsperCraft/towncraft#39]
Summary: Engines in Trin pack crafted from Engine Hoist have chances of being bugged and if started, will crash everyone and the server. You cannot fill them with fuel them either.

Steps to reproduce:

   1. craft the engine. (You will have to repeat this step a lot).
   2.  Once you get the bugged engine, put it in a vehicle and then try to fuel with a pump. (You should not be able to fuel it.)
   3. Attempt to start the engine. You should be crashing on this step.

Expected result: being able to use the engine without crashing and able to fill them with fuel.

Actual result: engine cannot be fuelled and will crash the server if it is started.

Note: I have not yet confirmed if other packs have this issue.

Crash log: https://paste.dimdev.org/mokavovaso.mccrash

**Comment by Linux-MissingNo** [comment]
This issue seem to be random engines from trin pack.

**Comment by ProsperCraft** [comment]
Mod has been reworked, let me know if it is still an issue.
