### ISSUE TITLE
Mine Colonies Logger Chest Client non responsive. 

### ISSUE THREAD

**Issue by nytstar** [ProsperCraft/towncraft#4]
[latest.log](https://github.com/ProsperCraft/towncraft/files/1876547/latest.log)

**Comment by ProsperCraft** [comment]
Please add more description, the log doesn't say anything.
Add how to reproduce the problem.

**Comment by nytstar** [comment]
im not sure where to pull any other logs from.. its not crashing i eventually have to close application because it just wont budge. if there is another location of logs let me know where i should pull form.

**Comment by Wissi** [comment]
Yeah I can confirm it happens. When you access the LumberJack hut block (to access the GUI for hire/fire/build/repair/inventory, etc) the entire client will "freeze" I have waited for over 2 mins and then it will eventually show and I can interact. But once I press any of the GUI buttons it freezes again for another 1 - 2 mins. Other players have reported that their game will not "un-freeze" and instead just crash to desktop (might be RAM in those cases).
There are no client side log during this process, so not sure if there is anything in console during this process on the server side.  (I'll recheck client console during this and post if anything pops up.)
No reports of this has been made on the Minecolonies Github issues side, seems localized to this modpack.

**Comment by Wissi** [comment]
Confirmed Fixed and working in latest version now. 
Thanks @ProsperCraft you can close this issue now.
