### ISSUE TITLE
Starter home crashes SP world

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ProsperCraft/towncraft#40]
When I try to make a starter home, my singleplayer world crashes. 

OS: Linux Mint 19.3
32 gb ram
ATLauncher Log file:
https://paste.atlauncher.com/view/c5d58c77

Pastebin MC crash report
https://pastebin.com/mtj5Yj4c

**Comment by skylerJhall** [comment]
wow remarkable, our setup is very close. Im running kubuntu 19, ubuntu 19.10 with kde. 32gb of ram on a laptop. Also AT launcher. same crash report. Have you tried MP?

**Comment by skylerJhall** [comment]
same crash?

**Comment by ProsperCraft** [comment]
I can not reproduce this, have made many worlds and not had a single crash.

Can you give me specific steps to reproduce?

**Comment by ClaudiusMinimus** [comment]
> wow remarkable, our setup is very close. Im running kubuntu 19, ubuntu 19.10 with kde. 32gb of ram on a laptop. Also AT launcher. same crash report. Have you tried MP?

What is MP?

**Comment by ProsperCraft** [comment]
Multiplayer.

**Comment by ClaudiusMinimus** [comment]
Sorry, its late - of course MP is Multiplayer... duh
I tried to load up the MP world, but the default one said my install was not compatible. 

This is a recent log when I crashed with TownCraft TWO-0.10 in SP
I downloaded the pack, created a world, went into creative to find a spot for the house, switched back to survival, and attempted to place the house. The world closed and the client crashed.

https://paste.atlauncher.com/view/32eee030

I then opened up my SP to Lan, though not sure this will make a difference, but it crashed too.
https://paste.atlauncher.com/view/234b7a8d

Do you know of any servers running version 0.10?

Thanks,
CM

**Comment by ProsperCraft** [comment]
The server is running 0.11 just waiting for Curseforge to approve it.

**Comment by ProsperCraft** [comment]
Please share your crash logs, those are client latest.logs which are helpful as well.
