### ISSUE TITLE
Quest item removed by crafttweaker

### ISSUE THREAD

**Issue by braingkk** [ProsperCraft/towncraft#42]
Pack Version: 4.6
SMP/MP: either
Crash log: N/A

Techguns questline requires Nightvision goggles that are hidden with Crafttweaker.

591  #Remove NV goggles recipe
592
593  removeAndHide(<techguns:nightvisiongoggles>);

https://puu.sh/FdSIA/f0ce25fb78.png
https://puu.sh/FdSHa/e391a3a347.png
https://puu.sh/FdSI4/f835874cfc.png

**Comment by ProsperCraft** [comment]
Removed the quest thank you.

The goggles were removed because they caused major performance issues.
