### ISSUE TITLE
(Ancient Towncraft v0.95) New World doesn't start you in Betweenworld

### ISSUE THREAD

**Issue by Faultygaming** [ProsperCraft/towncraft#43]
Steps to reproduce: install v0.95, Select Singleplayer, Create new world. This starts you in the Overworld.

Steps for workaround: install v0.93, create world as normal, save and quit, update to v0.95. Wipe out /mods/mellionaire and /mods/mellionaire-custom. Launch world, accept Forge prompts.

**Comment by ProsperCraft** [comment]
Would you please try removing default settings on a fresh install and see if it still happens?

**Comment by ProsperCraft** [comment]
I ran the test- 
https://gitlab.com/jomcraft-sources/defaultsettings/issues/13

**Comment by ProsperCraft** [comment]
Fixed.
