### ISSUE TITLE
[TownCraft TWO] 1.15.2 Recipe conflict for sleeping bag

### ISSUE THREAD

**Issue by toruPuchuu** [ProsperCraft/towncraft#45]
For TownCraft 1.15.2, there is a recipe conflict for Comforts' Sleeping Bag; Absent By Design's wool slab crafts instead.
TownCraft Version: 0.15
Minecraft Version: 1.15.2 (modded) forge-31.1.27

Thanks

**Comment by ProsperCraft** [comment]
1.15 was dropped, let me know if this is still an issue in 1.16.5
