### ISSUE TITLE
Dust not properly working after recent update 6.0

### ISSUE THREAD

**Issue by Dontrell94** [ProsperCraft/towncraft#48]
With update 6.0, the ability to use dusts in certain furnaces (futurepack and Thermal Expansion) has been removed while retaining the recipe in JEI. Testing was done with iron dusts but all dusts usable in a Mekanism processing setup is affected (personally tested 4 of them). The only current fix is to run them through an alloy smelter at the moment.

**Comment by ProsperCraft** [comment]
Let me know if this is still an issue in 8.12
