### ISSUE TITLE
Recipe for generator not entirely accurate. update 6.0

### ISSUE THREAD

**Issue by Dontrell94** [ProsperCraft/towncraft#49]
The recipe for the Tech Reborn Generator lists the ability to use an RE battery from Industrial Craft 2 in JEI. Was unable to craft with IC2 Battery at all, but was able to craft it using only a battery from Tech Reborn. The recipe in JEI does show the ability to use either battery, but was unable to reproduce only with an RE-Battery.

**Comment by ProsperCraft** [comment]
Fixed in 8.12 thank you for reporting it and Reveter for fixing it.
