### ISSUE TITLE
Bringing a sword to a gunfight quest - somewhat impossible

### ISSUE THREAD

**Issue by localzuk** [ProsperCraft/towncraft#5]
So, I have managed to kill 5 zombies, but regardless of what skeletons I kill (I've killed those with bows, though they wore modded armor, as well as the gun toting ones) and the number never increases.

I think the issue is that because of the other mods' mobs being so common, default mob spawning is very rare. I'm going on 4 hours searching and haven't found a single "default" skeleton.

Can I suggest altering the quest to make it somewhat achievable - either by improving default mob spawning, or by changing which mob that needs killing to include the gun toting skeletons?

EDIT: Actually, I just spawned in 5 skeletons using spawn eggs, and the kills didn't register at all.

**Comment by ProsperCraft** [comment]
The plan is to remove that quest because registering kills has been wonky

**Comment by owen-pi** [comment]
I changed the quest to zombie farmers and techguns skellys, tell me if you have issues. Also, you will need to log into the public server to obtain the quest update.
