### ISSUE TITLE
Crash from Runecraft mod. 6.0

### ISSUE THREAD

**Issue by Dontrell94** [ProsperCraft/towncraft#50]
When trying to extract the last page from the magical book from Runecraft (runecraft:magical_book) it causes a crash to main menu. Upon logging back in, the item was dropped onto the ground with 0/20 durability.

**Comment by Dontrell94** [comment]
upon crafting multiple times with said mod, it seems the math for crafting is really badly off and allows for duping of runes.

**Comment by ProsperCraft** [comment]
Runecraft is slated for removal next update.  It has been abandoned and has many problems.
