### ISSUE TITLE
Water and lava not able to be placed after server update. 7.0

### ISSUE THREAD

**Issue by Dontrell94** [ProsperCraft/towncraft#51]
After update 7.0, I know that some plugins and mods were updated. I believe that the configs for one of the plugins were reset. I believe it's essentials that was reset as the issue is the same as ones listed here:

[https://bukkit.org/threads/unable-to-place-water-on-my-server.44830/](url)
[https://bukkit.org/threads/how-do-i-allow-my-players-to-use-lava-buckets-and-flint.235883/](url)

Issue was confirmed by myself, KalitaNite, Izeburg, and Jokeruwd.

The issue seems to be from one of the following in the essentials config.yml:

General physics/behavior modifications
prevent:
lava-flow: true
water-flow: true
water-bucket-flow: true
fire-spread: true
lava-fire-spread: true

Which blocks should people be prevented from placing
placement: 46,327

Which items should people be prevented from using
usage: 327

I am not ruling out a possible exception thrown by mohist or something else, the bit of research I did pointed to essentials as the first culprit to similar issues. I also saw possible issues from plugins like World Guard.

And I can grab a video clip if necessary.

**Comment by ProsperCraft** [comment]
Essentials timestamp on last change was - April 15th 2020

 prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false

  blacklist:

    # Which blocks should people be prevented from placing?
    placement: 10,11,46,327,12236

    # Which items should people be prevented from using?
    usage: 327

**Comment by ProsperCraft** [comment]
Worldguard timestamp on last change 5/26/2017- 

    protect-against-liquid-flow: false

The world files for worldguard are blank or commented out.

No config file changes, Mohist changed and mods updated.

**Comment by Dontrell94** [comment]
I will start searching mohist's git now for leads

**Comment by Dontrell94** [comment]
which version of mohist? 41 or recent on git?

**Comment by ProsperCraft** [comment]
44 from Jenkins

**Comment by Dontrell94** [comment]
issue was fixed, forgot to close issue
