### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by ColdFerrin** [ProsperCraft/towncraft#52]
Is it possible to distribute server files with the pack, or give more detailed install instructions?

**Comment by ProsperCraft** [comment]
Curseforge rejected them because I included Mohist Red - here you go
https://www.dropbox.com/s/ki0ssr7ye5rcqtd/TownCraft-7.0-Serverpack.zip?dl=1

**Comment by ProsperCraft** [comment]
I am working with them to get Mohist Red server binary approved as a third party non curseforge approved.

**Comment by ColdFerrin** [comment]
Thanks!! At least they exist. When i tried to install the pack with the instructions no one can connect.
