### ISSUE TITLE
[Suggestion] Name Pain

### ISSUE THREAD

**Issue by naqaden** [ProsperCraft/towncraft#53]
With this modpack's focus on [hosting a ton of players](https://www.curseforge.com/minecraft/modpacks/towncraft?comment=125), my mod [Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain/) could be useful for gauging how nearby players are doing health-wise, among other things. It's a light and configurable client-side mod that tweaks vanilla nameplates, supported on all of TownCraft's MC versions.

**Comment by ProsperCraft** [comment]
Please make separate projects for the forge version and the fabric version, when I go through updating mods by clicking the arrows in the client every day, I hate downloading fabric mods.

**Comment by naqaden** [comment]
I won't promise a split, but to understand the issue better, what client are you using?

**Comment by ProsperCraft** [comment]
Twitch client, this is what the other mod authors have done for pack makers like myself, having to muck through files to make sure we are getting the right file, or forgetting and launching with fabric mods then having to delete them and get the right file is not going to work for me, I don't add projects that either 1. don't host fabric mods in their project, or 2. do some magic to make one jar work on both platforms.

**Comment by naqaden** [comment]
I see... the Twitch client filters version results to match a profile's MC version, yet doesn't filter to match the modloader. That is a shame and I hope it gets updated. Even then, a pack maker still has to muck through files to find the right download between new (unstable) and old (outdated) versions in the version list. NP is currently clean in that regard but was recently such a mess.

In any case, thanks for reviewing and taking the time to explain - it's good feedback. I'll keep thinking on it. For me it's more sane to keep a mod contained in one project, and I think it's better for a mod's health/visibility. IMO this is a problem Twitch should and easily could fix. If something changes, including my mind, I'll try to remember to come back this!

**Comment by ProsperCraft** [comment]
We don't have to check the files though... that is the point, when updating the modpack you click on the arrow to update the mod to the latest version-

![image](https://user-images.githubusercontent.com/4427684/95690287-cd948600-0bd3-11eb-96e0-43c51a9d5017.png)

And if that "latest" version happens to be the fabric file, you get that instead of what you were expecting.

Twitch will not fix it, as they are passing the launcher to overwolf, but they have yet to produce anything that I have seen.

**Comment by naqaden** [comment]
Right, unless the newest file is unstable. Good point about Twitch. Hopefully it's already resolved in whatever the new client will be. Till then, I will at least make note to upload Forge versions last to alleviate this.

**Comment by naqaden** [comment]
An Overwolf newsletter posted May 27th gives us some hope on this issue:

> You can have a single project that includes files for Forge and separate files for Fabric, simply mark each file respectively. This also eliminates the need for 2 projects.
>
> We will show the app users the proper relevant file and show the 'update available' indication if there is one based on files.
> 
> This should make profile creation and modpacking an even better experience, which will help increase the use and popularity of your creations.

...

> We plan to release the client within the next month

**Comment by ProsperCraft** [comment]
Yes, I am familiar with the update.

There are still problems...here is an example... you subscribe to be notified about updates about the project that has both and the fabric version updates, you get pinged when you don't want to be pinged about fabric updates.

**Comment by naqaden** [comment]
Wouldn't that happen even if the project was split by mod loader, but still had multiple MC versions under each? In my case I'm currently supporting most Forge versions from 1.7.10 to 1.16.x and hope to continue. Anyway, thanks for taking a look again, and I'll understand if this issue should be closed.

**Comment by ProsperCraft** [comment]
If there is a forge project and a fabric project you can follow the one you want, so you don't get notified for a modloader you don't use.

Also fabric doesn't get credit for downloads that it didn't produce.

**Comment by naqaden** [comment]
Right, and I'm pointing out how followers would still be notified about the 9 different versions of Forge I support. There's no escaping unwanted notifications, except to unfollow and lose the ones we want too.

I didn't understand the point about Fabric getting credit.
