### ISSUE TITLE
broken quest rewards

### ISSUE THREAD

**Issue by SkyBlockKing** [ProsperCraft/towncraft#55]
the removal of the animania mod broke several quests if these could be replaced with vanilla spawn eggs or possible bring animania back that would be great cus the spawn eggs would be super useful
![image](https://user-images.githubusercontent.com/73445794/97119482-df534e80-16e6-11eb-9f87-81f9feb9fddb.png)
![image](https://user-images.githubusercontent.com/73445794/97119491-e8dcb680-16e6-11eb-84a4-2826bb4f30e7.png)
![image](https://user-images.githubusercontent.com/73445794/97119499-f2661e80-16e6-11eb-87a5-f62d9e04b887.png)
![image](https://user-images.githubusercontent.com/73445794/97119521-25101700-16e7-11eb-9125-94b0b31baa1b.png)

**Comment by ProsperCraft** [comment]
No longer broken in 8.12
