### ISSUE TITLE
Iridium Neutron Reflector (Tech Reborn) Uncraftable

### ISSUE THREAD

**Issue by Ayvalen** [ProsperCraft/towncraft#57]
After updating the modpack to 8.9.1 I discovered that the Iridium Neutron Reflector no longer has a craftable recipe. The Ion Thruster requires two of these to be able to craft it. As such it is impossible to upgrade the Power Armor to have flight capabilities. I spoke w/ Reveter about it on the Discord and he mentioned it had something to do with downgrading Tech Reborn and that the recipe that was in place for the item was erased.

**Comment by ProsperCraft** [comment]
Fixed in 8.12
