### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SebastynDevlin** [ProsperCraft/towncraft#59]
Not sure what the cause of said leak is, however my Minecraft is currently using around 150% of the allocated ram I have, its gotten up to 11.2gb and is currently hitting page file rather often. 

Attached are both of my latest logs in the hopes that whatever is the cause of it is in this 

[FP-Latest.log](https://github.com/ProsperCraft/towncraft/files/6618732/FP-Latest.log)
[latest.log](https://github.com/ProsperCraft/towncraft/files/6618733/latest.log)

**Comment by ProsperCraft** [comment]
This is expected with a pack with so many blocks to build with, at one point it took over 20 gigs to run the pack.
