### ISSUE TITLE
After Update 2.20 Crash

### ISSUE THREAD

**Issue by Raggady** [ProsperCraft/towncraft#6]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RF Lux (rflux)

https://pastebin.com/WxdwLRLu

**Comment by ProsperCraft** [comment]
Thank you for reporting,  I pulled the 1.20 update, and I will be pushing a new update today, hopefully curse has sorted out their database issues with rflux update.

**Comment by ProsperCraft** [comment]
Pack updated :)
