### ISSUE TITLE
[Towncraft Two] No easy way to get mob heads - Upgrading Mine Colonies Barracks is gated.

### ISSUE THREAD

**Issue by mummabia** [ProsperCraft/towncraft#63]
Hi - The Mine Colonies Barracks requires a Skeleton Head to upgrade it but there is no easy way to get a mob head.  The LoTR mod structures usually have them at the Orc Camps, but this version of the mod does not have structures.  While it is possible to get the skulls using the Charged Creeper vanilla method, it's not really a practical and logical option for a mod pack. Is it possible to add a mod to include mob heads, or change recipes within existing mods to use Wither Skulls?  Thanks.

**Comment by ProsperCraft** [comment]
If this is still an issue for you please feel free to re-open.
