### ISSUE TITLE
[Towncraft Two] MachineMuse's Modular Powersuits recipes missing

### ISSUE THREAD

**Issue by mummabia** [ProsperCraft/towncraft#64]
Hi - Some of the recipes are missing for the Powersuits mod.  

For example, Power Armor Leggings -> movement -> sprint assist.  There's no recipe in JEI and if you have the required items (specified from the ftb [website](https://ftbwiki.org/Sprint_Assist)) in your inventory, it does not give you the install option.

Same for Jet Boots.  

Thanks.

**Comment by ProsperCraft** [comment]
dev quit updating the mod, it was incomplete and removed from the pack.
