### ISSUE TITLE
Towncraft Three impossible to launch

### ISSUE THREAD

**Issue by DoricSan** [ProsperCraft/towncraft#66]
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/37.0.75.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/37.0.75.json

**Comment by DoricSan** [comment]
The .json is not available.

**Comment by ProsperCraft** [comment]
Use Curseforge not Multimc
