### ISSUE TITLE
Can't upgrade town hall to level 2

### ISSUE THREAD

**Issue by jjjworley** [ProsperCraft/towncraft#67]
Using TC 3 0.026. I give the builder the white, red and yellow banners, then he immediately puts them in storage in the basement, goes out to build the town hall, then comes back and asks for more banners. Repeated this several times. Building the medieval alternative town hall. I have had numerous troubles in the past with other mod packs with town hall banners.

**Comment by ProsperCraft** [comment]
Mod author says this is likely fixed in the latest builds.
