### ISSUE TITLE
Error during Start-Up.

### ISSUE THREAD

**Issue by FennecAird** [ProsperCraft/towncraft#7]
Same error on both Town craft and Ancient Towncraft. 

Following mod(s) have been identified as potential causes: Unknown. 

crash report generated is in text file.
[Crashlog.txt](https://github.com/ProsperCraft/towncraft/files/2127783/Crashlog.txt)

**Comment by ProsperCraft** [comment]
You are not giving enough ram to the modpack, it requires a lot of ram, please follow this video.

https://youtu.be/-uUr1VAnkcs
