### ISSUE TITLE
Keeps on crashing when i open my inventory ingame

### ISSUE THREAD

**Issue by MapleBacon123** [ProsperCraft/towncraft#70]
[crash-2023-02-12_22.49.10-client.txt](https://github.com/ProsperCraft/towncraft/files/10719518/crash-2023-02-12_22.49.10-client.txt)

**Comment by ProsperCraft** [comment]
Playing in single player?

Make a copy of your instance folder and in that instance please update all of the mods and see if it still happens.

If it still crashes remove flywheel mod and see if it still happens.

**Comment by MapleBacon123** [comment]
> 

Hey so just did both options and it didnt work so im now trying to reinstall it with profile backups deleted (dont worry i just started so im not losing any progress) But the issue arised when i downloaded FTB Ultimine, i could guess that could have cause by it   Edit:: It works so it could be due to that mod
