### ISSUE TITLE
Pack does not Start up Unknown Issue 

### ISSUE THREAD

**Issue by loricx** [ProsperCraft/towncraft#71]
Here is my Log I dont know how to fix that [latest.log](https://github.com/ProsperCraft/towncraft/files/11030072/latest.log)

**Comment by ProsperCraft** [comment]
com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded

Pretty self explanatory, you didn't increase the ram, please read the pack description.
