### ISSUE TITLE
[TownCraft 1.12.2-9.0] Chinjufu config file has incorrect filename - Fatally Missing Registry Entries

### ISSUE THREAD

**Issue by TigerWalts** [ProsperCraft/towncraft#72]
It looks like the Chinjufu mod changed the name of it's config file from `ChinjufuMod.cfg` to `chinjufumod.cfg`. The modpack uses a customized `ChinjufuMod.cfg` file to disable some biomes.

Mac and Linux machines will not find the customized file and will revert to defaults and add the biomes to the registry.
This means that if you have a Windows machine on one side and a Mac/Linux on the other, you will end up with mismatched registries.

The pack's config file should be renamed to `chinjufumod.cfg`.

**Comment by ProsperCraft** [comment]
delete the config file and let it regen on both sides, this will fix your issue.

**Comment by TigerWalts** [comment]
That is not the correct fix.

The modpack has a modified config file that removes biomes that are there by default.

Your suggested fix requires all players connecting the the server to also reset the config file. Any player running on Windows who does not know that they need to do this step will have a different biome registry to the server and will get an error when connecting.

It must be corrected in the modpack.
