### ISSUE TITLE
TP to serface

### ISSUE THREAD

**Issue by Marius-Ventrue** [ProsperCraft/towncraft#9]
i got to the top and jumped into the bedrock but nothing happen

**Comment by RainbowDash956** [comment]
Does not work on server for me either. Pack might possibly be dead as it hasn't been updated in a while.

**Comment by ProsperCraft** [comment]
Definitely not dead, it is super stable in its current version, and it's scary to update and bring in all of the untested changes.

If you read the pack description, it says in bold not to change the world name, if you do you need to copy the config over the one with the name of your world name so the worlddrop mod works.
